/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package allure.kotlin.sample

import kotlin.test.Test
import kotlin.test.assertTrue

class LibraryTest: TestBase() {
    @Test fun testSomeLibraryMethod() {
        val classUnderTest = Library()
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'")

        myTestStep("myName")
    }
}
